package minerful.index.comparator.allinone;

import minerful.index.SortingPolicy;

public enum CnsSortAllInOneDefaultPolicy implements SortingPolicy {
	SUPPORT_FAMILY_CONFIDENCE_INTEREST_FACTOR_HIERARCHY_LEVEL,
	BOUNDS_SUPPORT_FAMILY_CONFIDENCE_INTEREST_FACTOR_HIERARCHY_LEVEL
}